# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: diagrams-sandbox
version: '0.0.0'
github: "githubuser/diagrams-sandbox"
license: GPL-3
author: "nick hansen"
maintainer: "nick hansen"
# synopsis: A new Haskeleton package.
# description: diagrams-sandbox is a new Haskeleton package.
# category: Other

extra-source-files:
- LICENSE.md
- package.yaml
- stack.yaml

ghc-options: -Wall

default-extensions:
- NoMonomorphismRestriction
- FlexibleContexts
- TypeFamilies
- ConstraintKinds
- NamedFieldPuns

dependencies:
- base-noprelude
- protolude
- diagrams-core
- diagrams-lib
- diagrams-contrib
- diagrams-cairo
- mtl
- mwc-random
- colour
- vector

library:
  source-dirs: lib
  dependencies:
  - primitive
  - vector

executables:
  lfrac:
    source-dirs: src
    main: LFrac.hs
    dependencies:
    - diagrams-sandbox
    ghc-options:
    - -main-is LFrac.main
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

  fifteen:
    source-dirs: src
    main: Fifteen.hs
    dependencies:
    - diagrams-sandbox
    ghc-options:
    - -main-is Fifteen.main
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

# benchmarks:
#   diagrams-sandbox-benchmarks:
#     source-dirs: benchmark
#     main: Main.hs
#     dependencies:
#     - base
#     - diagrams-sandbox
#     - criterion
#     ghc-options:
#     - -rtsopts
#     - -threaded
#     - -with-rtsopts=-N

# tests:
#   diagrams-sandbox-test-suite:
#     source-dirs: test-suite
#     main: Main.hs
#     dependencies:
#     - base
#     - diagrams-sandbox
#     - tasty
#     - tasty-hspec
#     ghc-options:
#     - -rtsopts
#     - -threaded
#     - -with-rtsopts=-N
